model_predictor: SGAN_MPPI
params:
  dt: 0.2
  prediction_horizon: 1.75
  history_length: 8

  action:
    span: 360
    n_actions: 30
  
  cost: # Only applicable to MPC controller
    sigma:
      h: 0.3
      s: 0.3
      r: 0.6
    q:
      obs: 100.0
      goal: 1.0
      wind: 5.0
      dev: 1.0
    
    discrete_cost_type: "winding"
  
  predictor:
    path: '/home/socnav/arstr/RelationalGraphLearning/crowd_nav/data/output/zara2_12_model.pt'
    use_gpu: False
    num_samples: 20
    deviation_penalty: True
    use_sgan_action: False
    use_sgan_mode: False

  log_cost: True
